import { Ubuntu } from "next/font/google";
import "./globals.css";
import StickyFooter from "./components/footer";
import ButtonAppBar from "./components/appbar";
import { createTheme, ThemeProvider } from "@mui/material";
import theme from "./components/theme";

const ubuntu = Ubuntu({ 
  weight: '400', 
  subsets: ["latin"] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <ThemeProvider theme={theme}>
          <ButtonAppBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
